"""Append-and-sort Price directives to per-symbol files.

Output format (one file per commodity):

    ;; Auto-generated by beancount-price-fetcher.
    ;; Source: yfinance
    ;; DO NOT EDIT -- this file is overwritten on each run.

    2024-01-02 price SPY 300.00 USD
    2024-01-03 price SPY 301.00 USD
    ...

Files are append-and-sorted by date for human readability; deduplication
is enforced via an in-memory key set passed by the caller.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Iterable
from dataclasses import dataclass, field
from datetime import date
from decimal import Decimal
from pathlib import Path

from beancount.core import data
from beancount.parser import parser

from .models import FetchedPrice

logger = logging.getLogger(__name__)

HEADER_TEMPLATE = """\
;; Auto-generated by beancount-price-fetcher.
;; Source: yfinance
;; DO NOT EDIT -- this file is overwritten on each run.
"""

_DATED_RE = re.compile(r"^prices-\d{4}-\d{2}-\d{2}(\.gen)?\.bean$")


def is_dated_filename(name: str) -> bool:
    """True if ``name`` matches bean-price's dated-file pattern.

    Recognised shapes:
        ``prices-YYYY-MM-DD.bean``
        ``prices-YYYY-MM-DD.gen.bean``
    """
    return _DATED_RE.match(name) is not None


def render_price_line(price_date: date, commodity: str, amount: Decimal, currency: str) -> str:
    """Render a single ``YYYY-MM-DD price COMMODITY AMOUNT CURRENCY`` line."""
    return f"{price_date.isoformat()} price {commodity} {amount} {currency}"


def parse_price_file(path: Path) -> list[FetchedPrice]:
    """Parse an existing price file back into ``FetchedPrice`` records.

    Used for dedup-against-existing-logic and for the migrate step.
    Non-price directives in the file (comments, opens) are ignored.
    """
    if not path.exists():
        return []
    entries, errors, _ = parser.parse_file(str(path))
    if errors:
        for err in errors[:5]:
            logger.warning("parse issue in %s: %s", path, err.message)
    out: list[FetchedPrice] = []
    for entry in entries:
        if isinstance(entry, data.Price):
            amount = entry.amount.number
            if amount is None:
                continue
            out.append(
                FetchedPrice(
                    commodity=entry.currency,
                    quote_currency=entry.amount.currency,
                    date=entry.date,
                    price=Decimal(str(amount)),
                )
            )
    return out


def append_and_sort(
    target_path: Path,
    new_prices: Iterable[FetchedPrice],
    existing: Iterable[tuple[str, date]] | None,
) -> bool:
    """Append ``new_prices`` to ``target_path``, sort by date, dedup.

    Args:
        target_path: File to write. Created (with a header) if it doesn't exist.
        new_prices: Prices to write.
        existing: Optional iterable of ``(commodity, date)`` tuples already
            in the ledger proper (not in this file). Used to dedup against.

    Returns:
        True if any line was written; False if nothing changed (empty input
        or all deduped out).
    """
    existing_keys: set[tuple[str, date]] = set(existing or [])
    all_lines: dict[date, list[str]] = {}
    if target_path.exists():
        for fp in parse_price_file(target_path):
            existing_keys.add((fp.commodity, fp.date))
            all_lines.setdefault(fp.date, []).append(
                render_price_line(fp.date, fp.commodity, fp.price, fp.quote_currency)
            )

    to_write: list[FetchedPrice] = []
    for fp in new_prices:
        key = (fp.commodity, fp.date)
        if key in existing_keys:
            continue
        existing_keys.add(key)
        to_write.append(fp)

    if not to_write:
        return False

    for fp in to_write:
        all_lines.setdefault(fp.date, []).append(
            render_price_line(fp.date, fp.commodity, fp.price, fp.quote_currency)
        )

    sorted_dates = sorted(all_lines)
    new_content = HEADER_TEMPLATE
    for d in sorted_dates:
        for line in all_lines[d]:
            new_content += line + "\n"

    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(new_content)
    return True


@dataclass
class PriceWriter:
    """Batch writer that dedups across multiple writes.

    Tracks what it has written so a second ``write_commodity`` call for the
    same dates is a no-op.
    """

    prices_dir: Path
    _written_keys: set[tuple[str, date]] = field(init=False, default_factory=set)

    def __post_init__(self) -> None:
        self.prices_dir = Path(self.prices_dir)
        if self.prices_dir.exists():
            for path in self.prices_dir.glob("*.beancount"):
                if is_dated_filename(path.name):
                    continue
                for fp in parse_price_file(path):
                    self._written_keys.add((fp.commodity, fp.date))

    def _target_path(self, commodity: str) -> Path:
        return self.prices_dir / f"{commodity}.beancount"

    def write_commodity(self, commodity: str, prices: Iterable[FetchedPrice]) -> int:
        """Write ``prices`` to ``prices/<commodity>.beancount``; return count written.

        The returned count is the number of NEW lines actually added (after
        dedup against both the in-memory key set and the existing file).
        """
        prices_list = list(prices)
        to_write = [fp for fp in prices_list if (fp.commodity, fp.date) not in self._written_keys]
        if not to_write:
            return 0
        result = append_and_sort(
            self._target_path(commodity), to_write, existing=set(self._written_keys)
        )
        if not result:
            return 0
        for fp in to_write:
            self._written_keys.add((fp.commodity, fp.date))
        return len(to_write)
